---
language: minimal
os: linux
dist: bionic
sudo: required
services:
  - docker
env:
  global:
   - DOCKER_REPO=matthijsbos/nerdrage-base
   - DOCKER_TAG=latest
arch:
  - amd64
  - arm64

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
script:
  - docker build --pull -t ${DOCKER_REPO}:${TRAVIS_COMMIT::8}-${TRAVIS_CPU_ARCH} .
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push ${DOCKER_REPO}:${DOCKER_TAG}-${TRAVIS_CPU_ARCH} ; fi

stages:
  - name: build
  - name: deploy
    if: branch = master

jobs:
  include:
    - arch: amd64
      stage: deploy
      script: 
        - docker pull ${DOCKER_REPO}:${DOCKER_TAG}-amd64
        - docker pull ${DOCKER_REPO}:${DOCKER_TAG}-arm64
        - docker manifest create ${DOCKER_REPO}:${DOCKER_TAG} ${DOCKER_REPO}:${DOCKER_TAG}-amd64 ${DOCKER_REPO}:${DOCKER_TAG}-arm64
        - docker manifest push ${DOCKER_REPO}:${DOCKER_TAG}
  