---
language: generic
dist: bionic
sudo: required 
services:
  - docker

# before_script:
#   - docker login -u $DOCKER_USER -p $DOCKER_PASS

jobs:
  include:
    - name: build platform linux/amd64
      os: linux
      dist: bionic
      arch: amd64
      stage: build
      script:
        - docker build --pull --progress plain -t matthijsbos/nerdrage-base:latest-amd64 .
    - name: build platform linux/arm64
      os: linux
      dist: bionic
      arch: arm64
      stage: build
      script:
        - docker build --pull --progress plain -t matthijsbos/nerdrage-base:latest-arm64 .
    # - name: create manifest for multi platform image
    #   stage: manifest
    #   script: 
    #     - docker pull matthijsbos/nerdrage-base:latest-amd64
    #     - docker pull matthijsbos/nerdrage-base:latest-arm64
    #     - docker pull matthijsbos/nerdrage-base:latest-armv7
    #     - docker manifest create matthijsbos/nerdrage-base:latest matthijsbos/nerdrage-base:latest-amd64 matthijsbos/nerdrage-base:latest-arm64 matthijsbos/nerdrage-base:latest-armv7
    #     - docker manifest push matthijsbos/nerdrage-base:latest
  