---
language: minimal
os: linux
dist: bionic
sudo: required
services:
  - docker
env:
  global:
   - DOCKER_REPO=matthijsbos/nerdrage-base
before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
script:
  - docker build --pull -t ${DOCKER_REPO}:${TRAVIS_COMMIT::8}-${TRAVIS_CPU_ARCH} .
  - docker push ${DOCKER_REPO}:${TRAVIS_COMMIT::8}-${TRAVIS_CPU_ARCH}

jobs:
  include:
    - arch: amd64
      stage: build
    - arch: arm64
      stage: build
    # - name: create manifest for multi platform image
    #   stage: deploy
    #   script: 
    #     - docker pull matthijsbos/nerdrage-base:latest-amd64
    #     - docker pull matthijsbos/nerdrage-base:latest-arm64
    #     - docker pull matthijsbos/nerdrage-base:latest-armv7
    #     - docker manifest create matthijsbos/nerdrage-base:latest matthijsbos/nerdrage-base:latest-amd64 matthijsbos/nerdrage-base:latest-arm64 matthijsbos/nerdrage-base:latest-armv7
    #     - docker manifest push matthijsbos/nerdrage-base:latest
  